### ISSUE TITLE
Text cut off when changed default size in Windows settings

### ISSUE THREAD

**Issue by d-kar** [NHLGames/NHLGames#14]
I noticed this myself as I changed it to 150% and also people complain on reddit:
http://imgur.com/keHRemP
It is how it looks at 125%
At 150% it even worse.
I'm not a GUI expert, is there a way to fit it?

**Comment by NHLGames** [comment]
A workaround for this is to go to the .exe properties and disable scaling for high DPI settings

**Comment by jwallet** [comment]
did not experimented that, so it might be fixed

**Comment by NHLGames** [comment]
This is still an issue on high DPI displays such as my laptop:

![image](https://cloud.githubusercontent.com/assets/17696817/25568789/08adfcc6-2dd9-11e7-989f-fb7627acf074.png)

If I go into Properties -> Compatibility and check "Disable scaling on high DPI displays", it looks like this:

![image](https://cloud.githubusercontent.com/assets/17696817/25568796/322b8fc8-2dd9-11e7-8d9a-20873b82b107.png)

Still not very proportional though.

**Comment by jwallet** [comment]
i will have to turn that option on again, and give it another try

**Comment by jwallet** [comment]
weird thing.
i've set on two laptops and on my pc 150% dpi and i didn't see anything like your first capture. i always get the second one, even if i check "disable scaling" (it does not change anything when re lauching it btw)

the best i did when trying to fix this issue is that

<img width="537" alt="dpi3" src="https://cloud.githubusercontent.com/assets/23088305/25733440/165fcede-3127-11e7-8715-cdb00f6bc5a5.PNG">
<img width="593" alt="dpi" src="https://cloud.githubusercontent.com/assets/23088305/25733442/1661aa06-3127-11e7-9f61-3673bed3995a.PNG">
<img width="559" alt="dpi2" src="https://cloud.githubusercontent.com/assets/23088305/25733441/1660bf88-3127-11e7-8750-b20d9f848382.PNG">
