### ISSUE TITLE
Feature: Highlights Vids

### ISSUE THREAD

**Issue by nbcraft** [NHLGames/NHLGames#153]
Just a random idea, don't know if it's available, but:

Would it be possible to add highlights videos once they're available, maybe to the far right of the stream links sections.

Cheers and keep up the good work.

**Comment by jwallet** [comment]
do you mean when a game ends and its live stream is off the air, so it is ready to start whenever you like?

**Comment by nbcraft** [comment]
Hi, no I meant the 5-10 minutes Game Recap/Highlights videos.
What's available here for example: https://www.nhl.com/video/t-277753022

I don't know if that's available through NHL.tv and could be plugged into this app.
But I'd love to have the equivalent of http://www.dtmts.com/ into the app.
Just a thought.

**Comment by jwallet** [comment]
Ok, we do have legit access to it from the nhl api, but i don't think we will implement these recap anytime soon. Actually i won't, i don't have time to keep this up to date everytime it changes, it's easier to just visit their website, but i'm ok to leave it here for anyone to grab it. We will just have to agree where to show it on the UI.

**Comment by jwallet** [comment]
- take a look at how we get infos from NHL api using DownloadJsonScheduleAsync in downloader.vb.
[example htttp](http://statsapi.web.nhl.com/api/v1/schedule?startDate=2017-11-04&endDate=2017-11-04&expand=schedule.teams,schedule.linescore,schedule.game.seriesSummary,schedule.game.content.media.epg)
![image](https://user-images.githubusercontent.com/23088305/34807791-b6177390-f658-11e7-9bf0-097fc751cf15.png)
- you will have to get stream qualities also, like we do with the main stream for each cam/broadcaster, using the value in settings (great/better/best)
- new properties will be needed in game to add a new var for your recap and then a new class
- new class recap will need to have properties like gamestream.vb that we use for different complete streams, but because recap are not related to content.media.epg.NHLTV but epg.Recap, you will have to create this recap.vb
- don't forget to add the proper enum in enums.vb 
- if this recap feature depends on a config set by the user, you will need to add it to app.conf, add an new emum to appsettingsenum, initialise it in formInitializer, change the ui
- the recap icon can be located at the same place that we have the live icon, because the recap won't be available when a feed is live, so it makes sense to put it there.
- everything else will be evaluated in the code review, i might forget many more things to look at... like how to add the right arguments to the player to launch this stream .m3u8.
- oh yeah, make sure that this m3u8 is really available (having an .m3u8 link does not mean it's up), i use the class common.vb and use the class SendWebRequestAsync
- also everything (methods) as to be async / await

**Comment by NHLGames** [comment]
Hey just want to chime in here, unfortunately with the hosts file edit the recap feature won't work since we don't cache the keys for those streams on our server.  They are free so you should be able to access them without a hosts file edit, but that would be a hassle to constantly switch back and forth.

Ideally instead of a hosts file edit we would have some sort of local proxy that can forward the requests to our server or to NHL directly, and that way we can decide if it needs to go through the proxy or not.

**Comment by jwallet** [comment]
Agree with that . Adding already free streams is not the goal of the app. It is like the scoring sheet to the app. To hard to maintain. Adding all these features will be the same as adding a link to nhl scores without the pain of maintening the api change for this part and playing with a proxy or the hosts file

**Comment by nbcraft** [comment]
Fair enough, this made sense to me only if everything was already there and it was as simple as adding an already gathered stream link to each game.
This indeed sounds overly complicated for the benefits.

**Comment by jwallet** [comment]
since it's not worth it i m gonna close this issue, but we might have no problem with adding a button for each game panel to open a new tab to their own nhl.com/score page (live or final)

**Comment by nbcraft** [comment]
From the example link you gave above.

I thought it'd be as simple as throwing this in the streamer:
http://md-akc.med.nhl.com/mp4/nhl/2017/11/04/3ea1801f-3ab9-401b-98fa-337c5e022b23/1509837416136/asset_1800k.mp4

**Comment by jwallet** [comment]
yeah you are right, i just realize that recap stream don't use the same domain that paid streams, so this feature can be done

**Comment by NHLGames** [comment]
Oh weird, I thought the last time I looked into this they wouldn't play with the hosts edit, I guess I was wrong

**Comment by nbcraft** [comment]
Thank you for this @jwallet, the feature looks great and this is now hands down the best highlight vids quality you can get out there.
Major props 👌
