### ISSUE TITLE
Add media keys functionality for any media player

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#158]
On top of spotify, we could add standard media key support to play/pause any media player.  As per this suggestion:

https://www.reddit.com/r/nhl_games/comments/7tkobq/v1113_released_allstar_game_fix/dtelueg/

**Comment by jwallet** [comment]
pretty sure this is a invalid issue, see the reply i wrote

**Comment by NHLGames** [comment]
Ah I didn't realize this feature already existed - does it only work with Windows Media Player though or other apps as well?

**Comment by jwallet** [comment]
it only simulates the media keys from a keyboard (even those without those keys), play and pause, if a media player responds to these kind of keyboard commands and it's running with a playlist paused, it should work. does not work if mpc is the streamer because mpc is detected as a music player. only one media player should be open, because only one will play/pause at at time, and it will be random
