### ISSUE TITLE
Can't find hosts file

### ISSUE THREAD

**Issue by cal2391** [NHLGames/NHLGames#167]
I'm running it in Windows 10 - initially on my D: drive but now on my C: drive in case that may have been an issue. 
It installs correctly, and asks for Admin Access to add the hosts file entry. I allow that, and then it asks "to add a line to my Windows Hosts file so it can redirect NHL.tv streams properly. Do I let NHLGames add its hostname to this file?"
Again, I allow that and get Failure with the following on the console:

[20:53:58] Status: Setting updated for 'MpcPath' to ''

[20:53:58] Status: Setting updated for 'SelectedLanguage' to 'English'

[20:53:58] Status: Setting updated for 'SelectedServer' to 'nhl.freegamez.gq'

[20:55:11] Error: Checking access to path: Could not find file 'C:\WINDOWS\system32\drivers\etc\hosts'.

[20:55:11] Fetching: Game schedule for 2018-02-12 from NHL.tv

I've gone through the hosts file dropdowns in settings to no avail and I've checked that the hosts file and it appears to be in the right location but no matter what I get the same error that the file can't be found

**Comment by jwallet** [comment]
Create one make sure it does not create a text file like hosts.txt but
hosts in the specified path

Le 12 févr. 2018 4:03 PM, "cal2391" <notifications@github.com> a écrit :

I'm running it in Windows 10 - initially on my D: drive but now on my C:
drive in case that may have been an issue.
It installs correctly, and asks for Admin Access to add the hosts file
entry. I allow that, and then it asks "to add a line to my Windows Hosts
file so it can redirect NHL.tv streams properly. Do I let NHLGames add its
hostname to this file?"
Again, I allow that and get Failure with the following on the console:

[20:53:58] Status: Setting updated for 'MpcPath' to ''

[20:53:58] Status: Setting updated for 'SelectedLanguage' to 'English'

[20:53:58] Status: Setting updated for 'SelectedServer' to 'nhl.freegamez.gq
'

[20:55:11] Error: Checking access to path: Could not find file
'C:\WINDOWS\system32\drivers\etc\hosts'.

[20:55:11] Fetching: Game schedule for 2018-02-12 from NHL.tv

I've gone through the hosts file dropdowns in settings to no avail and I've
checked that the hosts file and it appears to be in the right location but
no matter what I get the same error that the file can't be found

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NHLGames/NHLGames/issues/167>, or mute the thread

**Comment by jwallet** [comment]
so if you open Windows Explorer and paste this link "C:\WINDOWS\system32\drivers\etc\hosts" in the Path bar it should open the hosts file or ask you to open it using your favorite editor

**Comment by jwallet** [comment]
in the next version NHLGames will create the hosts file if it does not exists
