### ISSUE TITLE
60Hz Monitors and frame skipping

### ISSUE THREAD

**Issue by cloneman** [NHLGames/NHLGames#180]
This is not an NHLGames issue per se,but I've always had issues with stable 60fps playback on Windows on several different videoplayers. 
I feel like it skips a frame every 15 seconds. 

I workaround this problem by using 75Hz monitors, but I can't do that on my TV.

If anyone has any tips on fixing this it would nice.

**Comment by jwallet** [comment]
from another thread
> Do you run your monitors [including tv connected to graphic card] at different refresh rates? On Nvidia cards i know there can be problems displaying games and videos on 2 monitors at once with different refresh rates

**Comment by jwallet** [comment]
looked a bit on the Internet, apparently it can be an issue related to your graphic card. try to use the output option in settings, it works with vlc as the default player. it will save the live stream in the specified path, then you can watch that file instead of the m3u8, some people reported that some graphic card cannot render m3u8 hls stream properly but it works great when reading a recorded file like a .mp4

**Comment by jwallet** [comment]
reopen
