### ISSUE TITLE
"Error: No internet connection"

### ISSUE THREAD

**Issue by DancingPanther** [NHLGames/NHLGames#199]
Around 5 versions ago my computer decided to start fighting this program.

On launch, I see this: https://i.imgur.com/o3tfnTH.png?1

Clicking "no" results in this: https://i.imgur.com/qQYGxJv.png?1

Once it restarts, another prompt appears that says "do you let NHLGames change its host file" and I click yes, which results in  the "paste the console to the github page". So here we are. I clearly have internet access and I turned off my antivirus each time I've downloaded a new version for the last many months, and each time this exact error comes up. Thanks everyone- your hard work has allowed so many people to watch hockey!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NHLGames Bug Report v 1.3.0.0

Operating system: Microsoft Windows 8.1 64 Bits	
Internet: Connection test succeeded, ping google.com succeeded	
Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000	
Servers: NHLGames IP found (freesports.ddns.net)	
Hosts file: NHL.TV redirection is working (Hosts file tested) Entries: 127.0.0.1 nlsk.neulion.com; 107.6.182.249 mf.svc.nhl.com; 	
Selected player: MPV	
Streamer path: C:\Hockey\NHL Games\NHLGames_v1.3\livestreamer\livestreamer.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path: C:\Hockey\NHL Games\NHLGames_v1.3\mpv\mpv.exe [on form] [exe found]

Console log: 	
[23:51:48] Status: Setting updated for 'SelectedLanguage' to 'English'	
[23:51:48] Status: Setting updated for 'ShowSeriesRecord' to 'True'	
[23:51:48] Status: Setting updated for 'ShowLiveTime' to 'True'	
[23:51:48] Status: Setting updated for 'ShowTodayLiveGamesFirst' to 'True'	
[23:51:48] Status: Setting updated for 'SelectedServer' to 'freesports.ddns.net'	
[23:51:51] Status: No Internet access!	
[23:51:51] Fetching: Game schedule for 2018-05-20 from NHL.tv	
[23:51:51] Status: Server http://statsapi.web.nhl.com/api/v1/schedule seems down	
[23:51:51] Error: Failed to fetch games schedule.

**Comment by jwallet** [comment]
does this happen : 
- every refresh
- only when i launch the app, i have to refresh
- when i launch the app, but it's random
- right after my pc comes back from sleep mode

**Comment by DancingPanther** [comment]
It happens every time I launch the app, 100% of the time. It happens if I clear the error messages and refresh, each time, 100% of the time. It is not random, sleep mode does not affect it.

Here is my task bar: https://i.imgur.com/llEOXCI.png?1

I do not have malwarebytes or bitdefender.

This happens with no apps running every time too with no differences.

**Comment by jwallet** [comment]
this is what i was looking for 
![image](https://user-images.githubusercontent.com/23088305/40592570-0b22c96e-61ef-11e8-8d75-efd19c6b4b19.png)
(you can paste right in the reply box , instead of using imgur, it should upload what you have in your clipboard)

and if you can paste here a screenshot of your running apps CTRL + SHIFT + ESC, mostly your background running processes, if you don't want to paste it here, you can throw it in here : misterj.20@hotmail.com

**Comment by DancingPanther** [comment]
I cannot get rid of this error, I've resorted to using posted streams on r/NHLStreams.

![processes](https://user-images.githubusercontent.com/39475542/40638297-65a62b76-62d8-11e8-8656-12b85f84c5ec.png)

![taskbar](https://user-images.githubusercontent.com/39475542/40638341-c654db5c-62d8-11e8-89d1-6b53b2b3bdaa.png)

**Comment by jwallet** [comment]
is there country that have no access to google.com, where are you from ? because to see if you have internet it use your default internet connector (wifi in your case) and it pings `https://www.google.com`, i'm suspecting that it might be your internet connector, since you don't have any supicious app up there. if you want to put some screenshot in here, i would like to view how many internet adapters you have, you can cover any information you dont want to share on internet (like ip adress, name of your network, ...):
- right click on windows start button
- network connections menu
- Ethernet (side left menu)
- Change adapter options (blue link in related settings)
- print screen the new window

also, open `cmd.exe`.
- type `ping mf.svc.nhl.com`
- type `ping freegamez.ga`
- type `ping statsapi.web.nhl.com`
- type `ping google.com`
- screenshot if it fails, or take a screenshot of all , this is when it succeeds: `Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),`

**Comment by jwallet** [comment]
[nhlgames-debug-net.zip](https://github.com/NHLGames/NHLGames/files/2051917/nhlgames-debug-net.zip)

**Comment by DancingPanther** [comment]
![this is fun](https://user-images.githubusercontent.com/39475542/40693416-4aca3e02-6385-11e8-918e-e405ca0712af.png)
I believe this is what you wanted?

All pings succeeded.

I'm from Philly, def have internet here.

Same exact error messages from the debug version:

NHLGames Bug Report v 1.3.0.1

Operating system: Microsoft Windows 8.1 64 Bits	
Internet: Connection test succeeded, ping google.com succeeded	
Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000	
Servers: NHLGames IP found (freesports.ddns.net)	
Hosts file: NHL.TV redirection is working (Hosts file tested) Entries: 127.0.0.1 nlsk.neulion.com; 107.6.182.249 mf.svc.nhl.com; 	
Selected player: none	
Streamer path:  [on form] [exe not found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path: C:\Program Files\MPC-HC\mpc-hc64.exe [on form] [exe found]	
MPV path:  [on form] [exe not found]

Console log: 	
[21:17:05] Status: Setting updated for 'SelectedLanguage' to 'English'	
[21:17:05] Status: Setting updated for 'MpcPath' to 'C:\Program Files\MPC-HC\mpc-hc64.exe'	
[21:17:05] Status: Setting updated for 'VlcPath' to 'C:\Program Files\VideoLAN\VLC\vlc.exe'	
[21:17:05] Status: Setting updated for 'MpvPath' to ''	
[21:17:05] Status: Setting updated for 'StreamerPath' to ''	
[21:17:05] Status: Setting updated for 'ShowSeriesRecord' to 'True'	
[21:17:05] Status: Setting updated for 'ShowLiveTime' to 'True'	
[21:17:05] Status: Setting updated for 'ShowTodayLiveGamesFirst' to 'True'	
[21:17:05] Status: Setting updated for 'SelectedServer' to 'freesports.ddns.net'	
[21:17:05] https://www.google.com	
[21:17:05] Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'.	
[21:17:09] Status: No Internet access!	
[21:17:10] Fetching: Game schedule for 2018-05-29 from NHL.tv	
[21:17:10] Method not found: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'.	
[21:17:10] Status: Server http://statsapi.web.nhl.com/api/v1/schedule seems down	
[21:17:10] Error: Failed to fetch games schedule.

**Comment by DancingPanther** [comment]
Works like a charm. Thanks for chasing this man, I really appreciate it. You guys are fantastic
