### ISSUE TITLE
Ad Detection: Unexpected Exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by formerdaywalker** [NHLGames/NHLGames#237]
I use Google Play Music desktop player and it seems the ad detection only ever works on the beginning of ad breaks. When the stream comes back, the player does the opposite of whatever it was doing before. This means I can get weird breaks where there is an ad break and no music. The desktop version of google music does have an API that connects with Discord, much like Spotify.

Also, this warning comes up if it is related: [19:59:41] Warning: Ad Detection: Unexpected Exception: Object reference not set to an instance of an object.

**Comment by jwallet** [comment]
no need to open an issue for that, if someone wants to add an additional music service he will do it via a pull request. this app purposes is for streaming nhl games, so we will try to focus on that. sorry if your request is not taking, we do code in our free time and we want to focus on nhl games rather than music, you can enable `try with the detected media player` you might have better luck with that, but it's still play/pause, so it toggles the player status from its opposite status. if the player is set correctly before starting a game, it should toggle properly during ads.

i will do flag your issue as a bug for the second topic

**Comment by formerdaywalker** [comment]
Thanks!
