### ISSUE TITLE
24h-format

### ISSUE THREAD

**Issue by murko69** [NHLGames/NHLGames#271]
No real description needed I guess, but would be a great feature to be able to toggle between the two in the settings. 
I think the 24h format is more common and therefor more recognizable and/or familiar to many users, myself included, and seeing times in Calendar in24h format would be great!

Really only used in the Calendar I guess (and I also found 'time' in settings Live ReWind)

The Console log already presents things in 24h format for me, but I guess that's set to use system settings!?

**Comment by jwallet** [comment]
only to provide additional info, even if this can be easly added, the game times are provided by nhl.com, so that's their format, you can see they have this format displayed on their website.
![image](https://user-images.githubusercontent.com/23088305/89722765-9deeb500-d9bb-11ea-9221-a97bb36a4e67.png)
