### ISSUE TITLE
Schedule PVR for certain games

### ISSUE THREAD

**Issue by d-kar** [NHLGames/NHLGames#28]
Would be great if one could schedule to PVR games at game start.
If no streams yet available then show [PVR button](http://clip2net.com/clip/m216416/e2fb0-clip-33kb.png?nocache=1) under each team
Clicking on it will open "File Save" dialog, to chose a path to save a game file.
If team stream is not available at game start, then choose national stream, then other team stream.
When game is scheduled for PVR indicate that (perhaps change color from red to green and on mouse over show file name) and allow cancelling (by clicking on PVR again perhaps and confirming).

For Windows 7, can't use livestreamer output option, use VLC --sout option instead

**Comment by jwallet** [comment]
giving up this feature since we can replay a live game and record it, 
I don't think many people actually need a feature were you are unable to record a game because you won't have access to internet and you want to record while you are away from home and take your laptop with you to watch the game offline. they will just have to record manually then. to much effort, I will now be able to focus on other feature. maybe deliver mlbgames
