### ISSUE TITLE
Feature Request: Add option to select quality of stream to game selection

### ISSUE THREAD

**Issue by jingofett** [NHLGames/NHLGames#286]
**Describe the problem you encountered that your idea can resolve.**
To change the quality of the game you have to go to the settings page and manually change the stream quality.

**Describe the idea that you want us to add**
This might be a rare edge case but I like to watch one game in Excellent quality and put a couple of others on at Great quality to cut down on bandwidth use and to stop all the streams from lagging. Adding an option to change the quality of each game manually instead of blanket changing them all to the same quality, through the settings menu would be a nice quality of life upgrade.

**Screenshots**
(EDIT: My bad didn't realize the highlights button was in the top right x))
You could put a quality selection dropdown menu in this corner:
![image](https://user-images.githubusercontent.com/8313249/109048200-cc588700-76a4-11eb-8474-e6281d68dee8.png)

**Comment by jwallet** [comment]
I don't think this will add much value for the effort of redesigning the game panel completely to include this setting, the position you suggested is a row reserved for stream links and can be filled completely (below example is missing one though) 
![image](https://user-images.githubusercontent.com/23088305/123111978-57efe380-d40b-11eb-9c41-ee989ef10020.png)
If we add this setting to game panel, we will have to include other settings ("Live replay" and "Live rewind") as well to avoid confusion and then it will get messy (so that's why a redesign will be necessary)

So the workaround,
When you start a stream in 720p, you can go to settings change it to 540p and start a new game at this quality without affecting the previous game quality (720p), and then set the setting back to 720p... you will still have a game at 720p and a game at 540p.
